before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$STG_PRIVATE_KEY")
  - ssh-add <(echo "$PROD_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'



cache:
  paths:
    - node_modules/

stages:
  # - build
  - production
  - staging
  - pre-production

#build:
#  image: node:14
#  stage: build
#  only:
#    - staging
#  script:
#    - npm install
#    - npm run build

# test:
#   stage: test
#   script:
#     - dotnet test

staging:
  image : tuan1st/dotnetcore22 
  stage: staging
  only:
    - staging
  script:
    - echo "'Staging - Commit = $CI_COMMIT_SHORT_SHA'" > ./version.txt
    - rm ./src/environments/environment.ts
    - mv ./src/environments/environment.staging.ts ./src/environments/environment.ts
    - rsync -avIz -e "ssh -p $STG_SSH_PORT" --exclude-from="deploy_exclude.txt" ./* $STG_ACCOUNT@$STG_SERVER:$STG_DEPLOY_DIR/staging/cms
    - ssh $STG_ACCOUNT@$STG_SERVER "cd $STG_DEPLOY_DIR/staging/cms && npm install && ng build && echo 'Staging - Commit = $CI_COMMIT_SHORT_SHA' > $STG_DEPLOY_DIR/staging/cms/dist/v.txt"

# demo:
#   image : tuan1st/dotnetcore22 
#   stage: demo
#   only:
#     - demo
#   script:
#     - echo "'Staging - Commit = $CI_COMMIT_SHORT_SHA'" > ./version.txt
#     - rm ./src/environments/environment.ts
#     - mv ./src/environments/environment.demo.ts ./src/environments/environment.ts
#     - rsync -avIz -e "ssh -p $SSH_PORT" --exclude-from="deploy_exclude.txt" ./* $ACCOUNT@$SERVER:$DEPLOY_DIR/demo/cms
#     - ssh $ACCOUNT@$SERVER "cd $DEPLOY_DIR/demo/cms && npm install && ng build && echo 'Demo - Commit = $CI_COMMIT_SHORT_SHA' > $DEPLOY_DIR/demo/cms/dist/v.txt"

production:
  image : tuan1st/dotnetcore22 
  stage: production
  only:
    - master
  when: manual
  script:
    - echo "'Staging - Commit = $CI_COMMIT_SHORT_SHA'" > ./version.txt
    - rm ./src/environments/environment.ts
    - mv ./src/environments/environment.prod.ts ./src/environments/environment.ts
    - rsync -avIz -e "ssh -p $PROD_SSH_PORT" --exclude-from="deploy_exclude.txt" ./* $PROD_ACCOUNT@$PROD_SERVER:$PROD_DEPLOY_DIR/production/cms
    - ssh $PROD_ACCOUNT@$PROD_SERVER "cd $PROD_DEPLOY_DIR/production/cms && npm install && ng build && echo 'Production - Commit = $CI_COMMIT_SHORT_SHA' > $PROD_DEPLOY_DIR/production/cms/dist/v.txt"

pre-production:
  image : tuan1st/dotnetcore22 
  stage: pre-production
  only:
    - pre-production
  when: manual
  script:
    - rm ./src/environments/environment.ts
    - mv ./src/environments/environment.pre-prod.ts ./src/environments/environment.ts
    - rsync -avIz -e "ssh -p $PROD_SSH_PORT" --exclude-from="deploy_exclude.txt" ./* $PROD_ACCOUNT@$PROD_SERVER:$PROD_DEPLOY_DIR/pre-production/cms
    - ssh $PROD_ACCOUNT@$PROD_SERVER "cd $PROD_DEPLOY_DIR/pre-production/cms && npm install && ng build && echo 'Pre-Production - Commit = $CI_COMMIT_SHORT_SHA' > $PROD_DEPLOY_DIR/pre-production/cms/dist/v.txt"